import type { Metadata } from "next";
import localFont from "next/font/local"; // Make sure this import is correct
import "./globals.css"; // Ensure that the path is correct
import React from "react";
import Navbar from './products/navbar'
import Footer from './products/footer'

// Importing custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Setting up metadata for the application
export const metadata: Metadata = {
  title: "Fragrance Fusion",
  description: "Generated by create next app",
};

// Main layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}  
        <Navbar/>
        <Footer/>
      </body>
    </html>
  );
}
